### ISSUE TITLE
Investigate Vault Operator upgrade options

### ISSUE THREAD

**Issue by ramizpolic** [bank-vaults/vault-operator#85]
The Vault Operator API version needs to be upgraded both due to deprecated specs, but also due to recent migrations. 
Since the size of those changes will be quite large, we can also split them into multiple PRs. 
This way we can also address some underlying issues to simplify the impact of the upgrade process.

### Potential blocker
The migration from banzaicloud to bank-vaults is still not fully done as majority of the logic still references the previous project details. An issue with this is having to support backwards compatibility in two places (both in banzaicloud and in bank-vaults) projects. To address this, we should consider the following items:
- [x] Choice of the support/release path 
	- We can completely stop banzaicloud BV development, or we can switch the branding and have new BV components independent of banzaicloud. This is problematic since we would release a new product and the migration would be tricky. Good point is there are no references to previous projects, so we start fresh.
	- Keep with the banzaicloud references and only support one library. This is problematic since we need would keep the old references (does it qualify for CNCF?). The good part would be continuous development.

### Roadmap
- [ ] **PR-1** Create a mutating webhook to convert between versions
	- if we opt-in to change the Group (currently `vault.banzaicloud.com`) to another value while supporting backward compatibility, we might also want to handle resource control. Otherwise, we only need to convert the object params
- [ ] **PR-2** Assess public library usage across packages. Certain functionalities can be private, therefore we should decide which functionalities are okay to be public.
- **optional** 
	- Check if `pkg/apis/vault` can be simplified. 
	- Break vault controller logic into multiple files. There is too much logic declared in one file which can be easily split by context in the same module.

**Comment by ramizpolic** [comment]
This probably needs more coordination before jumping in, feel free to contribute @bank-vaults/maintainers

**Comment by ramizpolic** [comment]
BV Meeting notes: 
- We shall continue with supporting the current operator as is (keep the `vault.banzaicloud.com`), and if required, we will make adjustments towards renaming. However, this is not a priority.
-

**Comment by ramizpolic** [comment]
Closing this and moving the conclusions from this issue into separate ones.
